// Autogenerated from Pigeon (v10.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "pigeon.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}
static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface AlbumA ()
+ (AlbumA *)fromList:(NSArray *)list;
+ (nullable AlbumA *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation AlbumA
+ (instancetype)makeWithId:(nullable NSString *)id
    title:(nullable NSString *)title
    artist:(nullable NSString *)artist
    price:(nullable NSNumber *)price {
  AlbumA* pigeonResult = [[AlbumA alloc] init];
  pigeonResult.id = id;
  pigeonResult.title = title;
  pigeonResult.artist = artist;
  pigeonResult.price = price;
  return pigeonResult;
}
+ (AlbumA *)fromList:(NSArray *)list {
  AlbumA *pigeonResult = [[AlbumA alloc] init];
  pigeonResult.id = GetNullableObjectAtIndex(list, 0);
  pigeonResult.title = GetNullableObjectAtIndex(list, 1);
  pigeonResult.artist = GetNullableObjectAtIndex(list, 2);
  pigeonResult.price = GetNullableObjectAtIndex(list, 3);
  return pigeonResult;
}
+ (nullable AlbumA *)nullableFromList:(NSArray *)list {
  return (list) ? [AlbumA fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.id ?: [NSNull null]),
    (self.title ?: [NSNull null]),
    (self.artist ?: [NSNull null]),
    (self.price ?: [NSNull null]),
  ];
}
@end

@interface AlbumApiCodecReader : FlutterStandardReader
@end
@implementation AlbumApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [AlbumA fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface AlbumApiCodecWriter : FlutterStandardWriter
@end
@implementation AlbumApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[AlbumA class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface AlbumApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation AlbumApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[AlbumApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[AlbumApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *AlbumApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    AlbumApiCodecReaderWriter *readerWriter = [[AlbumApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void AlbumApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<AlbumApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AlbumApi.getAlbum"
        binaryMessenger:binaryMessenger
        codec:AlbumApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getAlbumWithError:)], @"AlbumApi api (%@) doesn't respond to @selector(getAlbumWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSArray<AlbumA *> *output = [api getAlbumWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
