import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'album.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'album.g.dart';

@freezed
class Album with _$Album {
  const factory Album({
    required String id,
    required String title,
    required String artist,
    required double price,
  }) = _Album;

  factory Album.fromJson(Map<String, Object?> json)
  => _$AlbumFromJson(json);
}